### ISSUE TITLE
Chests (including trapped) are invisible

### ISSUE THREAD

**Issue by Anderzenn** [OrigamiKing3612/OrigamiKings-Enhancement-Mod#12]
**Describe the bug**
Chests, including trapped chests, all are completely invisible in 1.19.4.

**To Reproduce**
1. Open the game
2. Get any chest from the mod
3. See that it's invisible

**Expected behavior**
I would expect the chests to be visible

**Screenshots**
![image](https://github.com/OrigamiKing3612/OrigamiKings-Enhancement-Mod/assets/12025450/fd96bb6c-bc34-418c-8cf2-077bde3530d0)
![image](https://github.com/OrigamiKing3612/OrigamiKings-Enhancement-Mod/assets/12025450/ad3ad273-e257-4ffe-aacd-aebbbc955d3a)
![image](https://github.com/OrigamiKing3612/OrigamiKings-Enhancement-Mod/assets/12025450/99ee617b-8aa5-47b4-9f78-637357717dcf)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.0.6

**Additional context**
I am not sure if this could be to do with my using the mod together with some other mods. But from what I know I don't have any mods that should interfere with the chests

**Comment by OrigamiKing3612** [comment]
I have been trying to fix this issue but I can't seem to figure it out, I have removed them for now. Maybe you could help me out? Thanks for the issue though 😀
