### ISSUE TITLE
Golden bar doors duping

### ISSUE THREAD

**Issue by nc-gp** [OrigamiKing3612/OrigamiKings-Enhancement-Mod#15]
**Describe the bug**
Duplicating golden bar doors.

**To Reproduce**
1. Craft golden bar doors
2. Place
3. Destroy
4. You will gain two from one.

**Expected behavior**
Duplicated golden bar doors.

**Screenshots**
![2023-07-16_01 54 27](https://github.com/OrigamiKing3612/OrigamiKings-Enhancement-Mod/assets/34553547/b607a32d-9e9e-4fc7-99c8-65346cab4da7)
![2023-07-16_01 54 32](https://github.com/OrigamiKing3612/OrigamiKings-Enhancement-Mod/assets/34553547/1b4da59b-c5b8-4875-9acf-63549269400d)
![2023-07-16_01 54 38](https://github.com/OrigamiKing3612/OrigamiKings-Enhancement-Mod/assets/34553547/f8ce7bc9-42ce-40b5-85aa-b89d4074746a)
![2023-07-16_01 54 40](https://github.com/OrigamiKing3612/OrigamiKings-Enhancement-Mod/assets/34553547/0b59afd8-fe01-4c7e-bc9a-634381b6aaf7)

**Desktop (please complete the following information):**
?

**Additional context**
quilt 0.19.2
minecraft 1.20

**Comment by OrigamiKing3612** [comment]
Fixed in 1.1.0-1.20.1
