### ISSUE TITLE
Golden bars are not craftable

### ISSUE THREAD

**Issue by nc-gp** [OrigamiKing3612/OrigamiKings-Enhancement-Mod#16]
**Describe the bug**
as title

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
![2023-07-16_01 59 47](https://github.com/OrigamiKing3612/OrigamiKings-Enhancement-Mod/assets/34553547/cd26a057-2b2a-4d27-b2c1-81047c206add)

**Desktop (please complete the following information):**
-

**Additional context**
quilt 0.19.2
minecraft 1.20

**Comment by OrigamiKing3612** [comment]
Sorry about that this will be fixed in the next update.
