### ISSUE TITLE
Missing recipes and textures

### ISSUE THREAD

**Issue by mxKeaton** [OrigamiKing3612/OrigamiKings-Enhancement-Mod#19]
**Describe the bug**
All of the custom chests and trapped chests are missing a crafting recipe and textures.
All custom ladders are missing recipes
Also it is very odd that I can not create vertical wooden slabs in the woodcutter, just in the stonecutter.

And you can not craft the woodcutter!

**Additional context**
I play on 1.19.2

**Comment by OrigamiKing3612** [comment]
Sorry about that, the 1.19.2 version was never really finished. Those issues should be fixed in the newest version.
